// app/layout.js
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Navbar from './_component/Navbar';
import "./background.css";

export const metadata = { title: "Create Next App", description: "Generated by create next app" };

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="flex flex-col min-h-screen">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <div className="el" />
          <Navbar />
          <main className="flex-1 pt-16">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}